Refactor the label-formatting code to be slightly less obtuse by combining the meny_sel/nsel beg/end variables into meny_normfmt & meny_pickfmt. Add meny_reset allowing more customisation of how (if at all) epameny should reset terminal attributes. Bail out if the version of Bash is <= v4.3 [from 2006] since we need features introduced at that point. Update help output & descriptions.

diff --git a/epameny b/epameny
--- a/epameny
+++ b/epameny
@@ -12,31 +12,46 @@
 # Use of this source code is governed by the Simplified BSD License:
 # https://opensource.org/license/bsd-2-clause
 
-meny_version='1.0'
+meny_version='1.0.1'
 
-meny_simple=${meny_simple:-0}
-meny_limit="${meny_limit:-1000}"
+if [ "${BASH_VERSINFO[0]}${BASH_VERSINFO[1]}" -lt 43 ]; then
+    echo "Bash version 4.3 or newer is required by epameny. Sorry." >&2
+    exit 1
+fi
+
+default_pickfmt="\033[7m::label::\033[7m"
 default_height=${LINES:-25}
 default_width=${COLUMNS:-80}
-meny_width="${meny_width:-$default_width}"
-meny_height="${meny_height:-$default_height}"
-meny_wrap="${meny_wrap:-0}"
-meny_sel_beg="${meny_sel_beg:-\033[7m}" # (SGR Invert)
+default_reset=0m # SGR: Reset
+
+meny_simple=${meny_simple:-0}
+meny_limit=${meny_limit:-1000}
+meny_width=${meny_width:-$default_width}
+meny_height=${meny_height:-$default_height}
+meny_wrap=${meny_wrap:-0}
+meny_reset=${meny_reset:-$default_reset}
+meny_pickfmt=${meny_pickfmt:-$default_pickfmt}
 meny_trimmark=${meny_trimmark:-...}
-trimcol=${meny_trimcol:-40%}
+trimcol=${meny_trimcol:-100%}
 
 (( meny_width += (meny_awidth) ))
 (( meny_height += (meny_aheight) ))
-
 if [[ "${trimcol: -1}" == '%' ]]; then
     (( trimcol = (${trimcol:0:-1} * meny_width) / 100 ))
 fi
 trimcol_len=${#meny_trimmark}
-
 (( marker_fit = meny_width >= trimcol_len ))
 (( trim_align = meny_width * (trimcol > meny_width / 2) ))
 (( head_align = meny_width - trimcol_len ))
 head_len_lookup=("$trim_align" "$head_align")
+if [[ -n "$meny_normfmt" ]]; then
+    norm_beg=${meny_normfmt/::label::*/}
+    norm_end=${meny_normfmt/*::label::/}
+fi
+if [[ -n "$meny_pickfmt" ]]; then
+    pick_beg=${meny_pickfmt/::label::*/}
+    pick_end=${meny_pickfmt/*::label::/}
+fi
 
 show_usage() {
     local self=$(basename "$0")
@@ -47,15 +62,14 @@ Usage:
   $self <label> <value> [<label> <value>] [...]
   meny_simple=1 $self <label> [label] [...]
 
-Creates an interactive menu consisting of one or more label/value-pairs.
-Once an item is confirmed, the associated item index & value is printed
-to standard output for the caller to capture & process. The menu itself
-is printed to standard error. In simple-mode (meny_simple=1), all items
-are treated as labels with values set to '::' (see below).
+Creates an interactive menu consisting of one or more label/value-pairs. \
+Once an item is confirmed, the associated item index & value is printed \
+to standard output for the caller to capture & process. The menu itself \
+is printed to standard error. In simple-mode (meny_simple=1), all items \
+are treated as labels with values set to '::' (see below). \
 $self supports vertical scrolling, & width-trimming of labels.
 
 Indexes count from 0: The first item is index 0, the fifth is index 4.
-A negative default index can be used to select items in reverse order.
 
 Keys:
   Up, l, A / Down, j, B  - Move the selection up / down.
@@ -69,41 +83,43 @@ Exit states:
                            except when the selected value is '::quit::'.
 Configurable varibles:
   \$meny_pick             - The default picked selection item index.
+                           Negative values count backwards from the last item.
   \$meny_simple           - Treat all items as labels with values set to '::'.
   \$meny_width            - Max. menu width (see also trim options).
   \$meny_height           - Max. number of items to display on the screen.
   \$meny_limit            - Max. number items to hold in the scroll-buffer.
   \$meny_wrap             - 0: Menu stops on its ends. 1: Menu wraps around.
-  \$meny_sel_beg          - Left-side text for the selected item.
-  \$meny_sel_end          - Right-side text for the selected item.
-  \$meny_nsel_beg         - Left-side text for non-selected items.
-  \$meny_nsel_end         - Right-side text for non-selected items.
+  \$meny_reset            - ANSI sequence printed at start & after each item.
+  \$meny_pickfmt          - Label-format for the selected item.
+  \$meny_normfmt          - Label-format for all other items.
   \$meny_awidth           - Formula or value to add to \$meny_width.
   \$meny_aheight          - Formula or value to add to \$meny_height.
   \$meny_trimmark         - Text shown at \$meny_trimcol on trimmed labels.
-  \$meny_trimcol          - Trim long labels on this column.
+  \$meny_trimcol          - Trim long labels on this column position.
                            Represents % of terminal width when ending with '%'.
-  Default values:
-    \$meny_pick           - 0        Index 0 (the first item)
-    \$meny_simple         - 0        Disabled, $self expects label/value-pairs.
-    \$meny_width          - \$COLUMNS if present, or 80 if not.
-    \$meny_height         - \$LINES   if present, or 25 if not.
-    \$meny_limit          - 1000     For unlimited items, set it to 0.
-    \$meny_wrap           - 0        Wrapping is disabled (menu stops at ends).
-    \$meny_sel_beg        - "\\e[7m"  ANSI sequence for inverting color.
-    \$meny_trimcol        - 45%      Trim at the centre(ish) of labels.
-    \$meny_trimmark       - '...'   Shown on the \$meny_trimcol column.
+Default values:
+  \$meny_pick             - 0    (the first item added is the default item)
+  \$meny_simple           - 0    (disabled: items must contain a label & value)
+  \$meny_wrap             - 0    (disabled: menu doesn't wrap around)
+  \$meny_width            - auto (\$COLUMNS if \$COLUMNS is set, otherwise 80)
+  \$meny_height           - auto (\$LINES   if \$LINES is set, otherwise 25)
+  \$meny_limit            - 1000 (keep at most 1000 items in total)
+  \$meny_trimcol          - 100% (labels too long get trimmed at the end)
+  \$meny_trimmark         - ...  (on trimmed tails, show ... at \$meny_trimcol)
+  \$meny_pickfmt          - ${default_pickfmt@Q} (invert colors)
+  \$meny_reset            - ${default_reset@Q} (default colors)
 
-  As nosel/onsel variables might contain non-printable text (e.g ANSI), their
-  string lengths are not considered during label-trimming calculations.
-  As \$meny_width + \$meny_awidth = effective width, a workaround is to set
-  \$meny_awidth to the longest nosel/onsel-width used. For example if
-  \$meny_nsel_beg='>' & \$meny_sel_end='(select)', meny_awidth should
-  be set to -8 (the width of the '(select)'-text) to prevent width-overflow.
+The length of a label is computed without consideration of ANSI escape codes. \
+Similarly, meny_pickfmt & meny_normfmt is also not considered. meny_awidth \
+can be used to adjust the width-calculation if needed. For example if \
+\$meny_normfmt='\\e[1m->::label::', meny_awidth should be set to -2 to \
+account for the arrow whilst ignoring the invisible ANSI code for bolding it.
 
-Special labels & values (not applicable when meny_simple=1):
-  A label or value set to '::' will copy the other field's content.
-  A value set to '::quit::' behaves the same as if 'q' was pressed.
+Placeholders:
+  meny_pickfmt & meny_normfmt use '::label::' as a placeholder for labels.
+  In normal mode (i.e meny_simple=0), the following applies to labels/values:
+  A value set to '::' is substituted by its label & vice-versa.
+  A value set to '::quit::' will upon selection act as if 'q' was pressed.
 
 Examples:
   $self 'A label' 'A value'
@@ -119,7 +135,7 @@ ansi()  { scrbuf+="\033[$*"; }
 #goto_next_row()    { ansi "$1B"; } # CUD: Cursor Dn (doesn't scroll)
 goto_prev_row()     { ansi "$1A"; } # CUU: Cursor Up (doesn't scroll)
 goto_col()          { ansi "$1G"; } # CHA: Cursor Horisontal Absolute
-reset_color()       { ansi 0m; }    # SGR: Reset
+reset_color()       { ansi "$meny_reset"; }
 clear_to_end()      { ansi J; }     # ED: Erase In Display
 goto_next_row_alt() { write "\n"; } # Emulate CNL
 goto_prev_row_alt() { goto_prev_row "$1"; goto_col 1; } # Emulate CPL
@@ -211,8 +227,8 @@ render_items() {
         clear_to_end
         (( index = buf_offs + i ))
         (( index == pick )) \
-            && write "$meny_sel_beg${item_labels[$index]}$meny_sel_end" \
-            || write "$meny_nsel_beg${item_labels[$index]}$meny_nsel_end"
+            && write "$pick_beg${item_labels[$index]}$pick_end" \
+            || write "$norm_beg${item_labels[$index]}$norm_end"
         reset_color
         (( i < meny_height - 1 )) && goto_next_row_alt
     done
